### ISSUE TITLE
Methods with multiple annotations may throw ClassCastException

### ISSUE THREAD

**Issue by Iggle** [ebean-orm/ebean-agent#115]
Due to #114 during initial building of ClassMeta a ClassCastException may occur if the following are all true:

1. A method has multiple annotations
2. These annotations use the same value name (e.g. the literal String "value")
3. The first annotation visited describes a non-array value and the second annotation an array.

A stack trace may look like this:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at io.ebean.enhance.common.AnnotationInfo.getArrayEntry(AnnotationInfo.java:44)
	at io.ebean.enhance.common.AnnotationInfoVisitor.<init>(AnnotationInfoVisitor.java:20)
	at io.ebean.enhance.common.AnnotationInfoVisitor.create(AnnotationInfoVisitor.java:42)
	at io.ebean.enhance.common.AnnotationInfoVisitor.visitArray(AnnotationInfoVisitor.java:37)
	at io.ebean.enhance.asm.ClassReader.readElementValue(ClassReader.java:2940)
	at io.ebean.enhance.asm.ClassReader.readElementValues(ClassReader.java:2759)
	at io.ebean.enhance.asm.ClassReader.readMethod(ClassReader.java:1182)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:688)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:400)
	at io.ebean.enhance.common.ClassMetaReader.readFromResource(ClassMetaReader.java:65)
	at io.ebean.enhance.common.ClassMetaReader.getWithCache(ClassMetaReader.java:33)
	at io.ebean.enhance.common.ClassMetaReader.get(ClassMetaReader.java:25)
	at io.ebean.enhance.common.EnhanceContext.getInterfaceMeta(EnhanceContext.java:223)
	at io.ebean.enhance.common.DetectEnhancement.visit(DetectEnhancement.java:96)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:533)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:400)
	at io.ebean.enhance.Transformer.detect(Transformer.java:379)
	at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:213)
	at io.ebean.enhance.Transformer.transform(Transformer.java:178)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:67)
	at io.ebean.enhance.maven.AbstractEnhance.executeFor(AbstractEnhance.java:73)
	at io.ebean.enhance.maven.MainEnhanceMojo.execute(MainEnhanceMojo.java:26)
```

The method visited may look like this:
```java
@POST
@ApiOperation(value = "Creates something")
@ApiResponses(value = { @ApiResponse(code=204) } )
void postStuff(Stuff param);
```

This is because the visitAnnotation Method in the inner Class MethodReader of ClassMeta always initializes an AnnotationInfoVisitor (regardless if it's `@Transactional` or not).
Because all AnnotationInfoVisitor instances share a single AnnotationInfo from the MethodMeta when getArrayEntry calls computeIfAbsent it will receive the previously saved String and try to cast to a List.

I'm not sure if the AnnotationInfoVisitor is supposed to visit annotations other than `@transactional`.

Otherwise one could either:

1. Create separate AnnotationInfo instances for different annotations on the same method
2. Adapt the key in the valueMap to include the AnnotationName. This might still create conflicts for Annotations of same name and depth in an array, say:
```java
@ApiOperation(authorizations = {
    @Authorization("APIKeyHeader")
    @Authorization("OAuth")
}
void getStuff();
```

**Comment by rbygrave** [comment]
Good work @Iggle . I have a failing test and follow what you have said here.

>  is supposed to visit annotations other than @transactional.

I think the agent is only really interested in 2 annotations `@Transactional` and `@TypeQueryBean` ... and it's only interested in `@TypeQueryBean` in order to determine the "version/style" of the code generated by querybean-generator (APT).  We changed/simplified the code generated for querybeans relatively recently hence the agent detects if it is enhancing the new style or old style of query beans.

My guts says the path forward is to only read annotation info for those 2 annotations ( `@Transactional` and `@TypeQueryBean`) and otherwise ignore.  I'm heading out for a bit ... I should get back to this later today but that is my current thinking.

Cheers, Rob.
PS: Thanks for the excellent bug report - great stuff !!
