### ISSUE TITLE
regression - updating agent from 12.1.10 to 12.1.12 on JDK11 causes NPE

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/ebean-agent#146]
@rbygrave, updated agent from 12.1.10 to 12.1.12 on JDK11 (not sure if this is a case on JDK8) and testing my custom 2 level cache implementation between several nodes in cluster. So, once I start JVM with following agent 
 `-javaagent:/Users/andreyborisov/.m2/repository/io/ebean/ebean-agent/12.1.10/ebean-agent-12.1.10.jar` all works as expected, but once i update it to
`-javaagent:/Users/andreyborisov/.m2/repository/io/ebean/ebean-agent/12.1.12/ebean-agent-12.1.12.jar` i start getting NPEs

```
javax.persistence.PersistenceException: java.lang.NullPointerException
	at io.ebeaninternal.server.deploy.BeanDescriptor.createReference(BeanDescriptor.java:2047)
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.manyPropLoad(BeanDescriptorCacheHelp.java:316)
	at io.ebeaninternal.server.deploy.BeanDescriptor.cacheManyPropLoad(BeanDescriptor.java:1415)
	at io.ebeaninternal.server.core.DefaultBeanLoader.loadManyInternal(DefaultBeanLoader.java:91)
	at io.ebeaninternal.server.core.DefaultBeanLoader.loadMany(DefaultBeanLoader.java:54)
	at io.ebeaninternal.server.core.DefaultServer.loadMany(DefaultServer.java:568)
	at io.ebean.common.AbstractBeanCollection.lazyLoadCollection(AbstractBeanCollection.java:98)
	at io.ebean.common.BeanList.init(BeanList.java:135)
	at io.ebean.common.BeanList.iterator(BeanList.java:329)
Caused by: java.lang.NullPointerException: null
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.setEmbeddedOwner(BeanPropertyAssocOne.java:682)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.setValueIntercept(BeanPropertyAssocOne.java:665)
	at io.ebeaninternal.server.deploy.id.IdBinderEmbedded.convertSetId(IdBinderEmbedded.java:483)
	at io.ebeaninternal.server.deploy.BeanDescriptor.convertSetId(BeanDescriptor.java:2370)
	at io.ebeaninternal.server.deploy.BeanDescriptor.createReference(BeanDescriptor.java:2027)
```

I assume it's very easy to reproduce with any L2 cache (redis/hazelcast) and put collection cache.

**Comment by rbygrave** [comment]
> reproduce

Can you show me the model of the entity bean here being loaded from cache?  We have L2 cache tests in the ebean build itself so we ultimately want a failing test added in there.

**Comment by turbospaces** [comment]
i guess the model itself is less important in this case, but will post snippet tomorrow. What I found is that once there is no clustering and communication between nodes, there is no such issue (in scope of 1 VM). So presumably it's not reproducible with regular in-VM communication. My second-level cache is based on jgroups and conceptually replicated hazelcast/infinispan cache implementation

**Comment by rbygrave** [comment]
Does this use Bean serialisation?   There was a change in the ebean-agent such that the internal properties were transient by default so maybe it's related to that.

**Comment by rbygrave** [comment]
https://github.com/ebean-orm/ebean-agent/commit/1265d1f10d6da5e56225a1e74ff7b002228c7866

So to test that theory ... have a ebean.mf file that contains:
```
transient-internal-fields: false
```

**Comment by rbygrave** [comment]
Note that Ebean provided L2 cache implementations (Redis, Hazelcast, Ignite) do not use Java serialisation.

**Comment by rbygrave** [comment]
Can you confirm if the issue is related to the change where `transient-internal-fields` now defaults to true?  (Pondering if that default should be reverted)

**Comment by rbygrave** [comment]
Any update @turbospaces  ?  Tried with `transient-internal-fields: true` ?

**Comment by turbospaces** [comment]
@rbygrave tried it with this flag, no difference

```
Caused by: java.lang.NullPointerException: null
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.setEmbeddedOwner(BeanPropertyAssocOne.java:682)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.setValueIntercept(BeanPropertyAssocOne.java:665)
	at io.ebeaninternal.server.deploy.id.IdBinderEmbedded.convertSetId(IdBinderEmbedded.java:483)
	at io.ebeaninternal.server.deploy.BeanDescriptor.convertSetId(BeanDescriptor.java:2370)
	at io.ebeaninternal.server.deploy.BeanDescriptor.createReference(BeanDescriptor.java:2027)
	... 32 common frames omitted
```

Bean serialization is being used in fact. So i simply push value to other nodes using jgroups on cache put

**Comment by rbygrave** [comment]
Are you able to create a failing test?

**Comment by rbygrave** [comment]
I think this is the same as:
```
java.lang.NullPointerException
	at test.model.Customer._ebean_get_name(Customer.java:6)
	at test.model.Customer.getName(Customer.java:53)
	at test.enhancement.SerializeEntityBeanTest.test(SerializeEntityBeanTest.java:32)
```

```java
public class SerializeEntityBeanTest extends BaseTest {

  @Test
  public void test() throws IOException, ClassNotFoundException {


    Customer customer = new Customer();
    customer.setName("hello");

    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    ObjectOutputStream oos = new ObjectOutputStream(baos);
    oos.writeObject(customer);
    oos.close();

    ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
    ObjectInputStream ois = new ObjectInputStream(bais);
    Customer bean = (Customer)ois.readObject();

    final String name = bean.getName();

    assertEquals("hello", name);
  }
}
```

**Comment by rbygrave** [comment]
@turbospaces  I think this should be fixed in ebean-agent 12.2.2, can you confirm that for me.

Thanks

**Comment by turbospaces** [comment]
@rbygrave - I tried to check it, but now somehow query-bean generator is not invoked as part of maven build (i haven't change maven settings file at all, just changed version of query-bean generator). i spent half of day debugging root cause as per http://www.javatronic.fr/articles/2014/08/31/how_to_make_sure_javac_is_using_a_specific_annotation_processor.html

Then i have checked this https://github.com/rzwitserloot/lombok/issues/1722 and it looks like static imports in annotation processors must be avoided as such.

I guess this commit https://github.com/ebean-orm/querybean-generator/commit/79c7f4c81de6d16a40e44eb04af637d9c8f2bbad where static imports were added could be the root cause of problem.

I suggest to remove all static imports and release new version of query-bean generator ASAP, since latest version simply doesn't work without any errors/exceptions

**Comment by turbospaces** [comment]
i have created https://github.com/ebean-orm/querybean-generator/issues/52 for this specific case

**Comment by rbygrave** [comment]
You should upgrade to the latest - 12.2.2 ... which includes the fix for
the NPE.

**Comment by turbospaces** [comment]
this is what i did before posting comment.  but i can't  confirm 12.2.2 until this is fixed ebean-orm/querybean-generator#52

**Comment by rbygrave** [comment]
@turbospaces  ... does this mean this is also fixed (in ebean-agent 12.2.2) ?

**Comment by rbygrave** [comment]
@turbospaces  ... this is fixed right ?

**Comment by turbospaces** [comment]
this is fixed now, you are right. I don't see any errors in logs anymore after perf test
