### ISSUE TITLE
java.lang.IndexOutOfBoundsException when enhancing class with certain construct

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/ebean-agent#148]
I *assume* the error is in Asm 7.3.1, because afaik the only important change between 12.1.10 and 12.1.11 is the upgrade of Asm. That said, the Asm in the agent is cloned/forked (patched?) so I want to ask here first.

The error is as as stated in the subject. 

The "funny" thing is that regardless if it's an entity bean, as long as it's scanned, it throws the exception, but the build completes successfully.

There's a minimal example in https://github.com/tobias-/example-minimal/pull/1

**Comment by rbygrave** [comment]
> the Asm in the agent is cloned/forked (patched?)

With ASM we take the source + commons source, repackage it into io.ebean.enhance.asm ... and remove the classes that we don't need (classes in commons, tree etc that we have no interest in).

We repackage into io.ebean.enhance.asm because:
-  that was always the recommendation from the ASM project
- means we don't have a version clash
- makes it easier to use as a javaagent (it is self contained)

We don't "patch" anything in io.ebean.enhance.asm ... at least we haven't needed to yet, we'd push any patch upstream if we did need to.

I'll try to have a look at this shortly.

**Comment by rbygrave** [comment]
```[INFO] --- ebean-maven-plugin:12.1.11:enhance (main) @ example-minimal ---
[INFO] classSource=/home/rob/github/other/bugs/example-minimal/target/classes  transformArgs=debug=2
[INFO] packages entity:[]  transactional:[]  querybean:[]  profileLocation:true
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:535)
	at io.ebean.enhance.asm.commons.AdviceAdapter.popValue(AdviceAdapter.java:593)
	at io.ebean.enhance.asm.commons.AdviceAdapter.visitVarInsn(AdviceAdapter.java:348)
	at io.ebean.enhance.asm.ClassReader.readCode(ClassReader.java:2383)
	at io.ebean.enhance.asm.ClassReader.readMethod(ClassReader.java:1492)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:717)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:401)
	at io.ebean.enhance.Transformer.transactionalEnhancement(Transformer.java:302)
	at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:232)
	at io.ebean.enhance.Transformer.transform(Transformer.java:181)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:148)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:132)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:66)
	at io.ebean.enhance.maven.AbstractEnhance.executeFor(AbstractEnhance.java:77)
	at io.ebean.enhance.maven.MainEnhanceMojo.execute(MainEnhanceMojo.java:26)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by rbygrave** [comment]
Ok, pretty comfortable that I've got to the bottom of this.

Effectively this is not to do with the update to ASM 7.3.1 but the profileLocation enhancement being turned on + specifically the ConstructorMethodAdapter + more specifically the asm.commons.AdviceAdapter.

So in 12.1.11 we started using this part of the enhancement by default (when we didn't in previous versions).  Now the asm.commons.AdviceAdapter does some things that we don't want it to do and this is a problem with the constructor code of `Owner.kt`.

The fix will be for ConstructorMethodAdapter to extend asm.commons.GeneratorAdapter.

-----
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.remove(ArrayList.java:502)
	at io.ebean.enhance.asm.commons.AdviceAdapter.popValue(AdviceAdapter.java:593)
	at io.ebean.enhance.asm.commons.AdviceAdapter.visitVarInsn(AdviceAdapter.java:348)
	at io.ebean.enhance.asm.ClassReader.readCode(ClassReader.java:2383)
	at io.ebean.enhance.asm.ClassReader.readMethod(ClassReader.java:1492)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:717)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:401)
	at org.example.TestAsmClassRead.main(TestAsmClassRead.java:40)

**Comment by tobias-** [comment]
Ok, so my bad on the 7.3.1.

As always, thanks for quick response. I have seen so many people shadow it that I assumed that they did that in byte code, not by copying it.

Currently we've worked around it by not using the result from the `.use {}` block. That said, I still think it's weird that Asm would crash parsing the file, so I'm curious on how the fix looks.

Either way, TIA

**Comment by rbygrave** [comment]
For future note a helpful test main method:

```java
package org.example;

//import org.objectweb.asm.ClassReader;
import io.ebean.enhance.asm.ClassReader;
import io.ebean.enhance.asm.ClassWriter;
//import io.ebean.enhance.asm.ClassWriterWithoutClassLoading;
import io.ebean.enhance.common.AgentManifest;
import io.ebean.enhance.common.ClassBytesReader;
//import io.ebean.enhance.common.ClassWriterWithoutClassLoading;
import io.ebean.enhance.common.ClassWriterWithoutClassLoading;
import io.ebean.enhance.common.EnhanceContext;
import io.ebean.enhance.entity.ClassPathClassBytesReader;
import io.ebean.enhance.transactional.ClassAdapterTransactional;
//import org.objectweb.asm.tree.ClassNode;
//import org.objectweb.asm.tree.MethodNode;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
//import java.util.List;

public class TestAsmClassRead {

  public static void main(String[] args) throws IOException {

    File file = new File("/home/rob/github/other/bugs/example-minimal/target/classes/org/example/domain/Owned.class");
    byte[] fileContent = Files.readAllBytes(file.toPath());

    final ClassLoader loader = TestAsmClassRead.class.getClassLoader();

    ClassBytesReader reader = new ClassPathClassBytesReader(null);
    AgentManifest manifest = new AgentManifest(loader);
    EnhanceContext enhanceContext = new EnhanceContext(reader, null, manifest);

    ClassReader cr = new ClassReader(fileContent);
    ClassWriterWithoutClassLoading cw = new ClassWriterWithoutClassLoading(ClassWriter.COMPUTE_FRAMES, loader);
    ClassAdapterTransactional ca = new ClassAdapterTransactional(cw, loader, enhanceContext);
//    ClassNode ca = new ClassNode();
    try {
      cr.accept(ca, ClassReader.EXPAND_FRAMES);

    } catch (Exception e) {
      e.printStackTrace();
    }

    //final List<MethodNode> methods = ca.methods;
    System.out.println("done ");
  }
}
```

**Comment by rbygrave** [comment]
Notes regarding this change:
- Pulled ConstructorMethodAdapter.visitMethodInsn() logic into ProfileMethodInstruction (unchanged)
- Change ConstructorMethodAdapter to extend MethodVisitor (from FinallyAdapter) ... so all try/finally aspects removed there
- Change FinallyAdapter so try catch only added when method is transactional.  So if method only has query bean profile location enhancement then no try catch added
- Change MethodAdapter to extend FinallyAdapter and get reuse of visitMethodInsn() via ProfileMethodInstruction

Changing from this to reproduce is a matter of changing ConstructorMethodAdapter to extend AdviceAdapter.  To me this suggests that there is an issue in AdviceAdapter wrt Constructor methods but I haven't had time to dig further and produce a test case.  At this point the thinking is to never use AdviceAdapter with constructor methods.

@tobias-  ... thanks a lot for the very narrowed down and minimal test case - excellent work !!

**Comment by tobias-** [comment]
@rbygrave thanks!
