### ISSUE TITLE
Improve exception thrown when incorrect collection type used for OneToMany or ManyToMany -  we are not allowed to use LinkedList or ArrayList as collection types.

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-agent#157]
```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "value" is null
        at io.ebean.enhance.asm.SymbolTable.hash(SymbolTable.java:1241)
        at io.ebean.enhance.asm.SymbolTable.addConstantUtf8Reference(SymbolTable.java:999)
        at io.ebean.enhance.asm.SymbolTable.addConstantClass(SymbolTable.java:513)
        at io.ebean.enhance.asm.MethodWriter.visitTypeInsn(MethodWriter.java:972)
        at io.ebean.enhance.entity.FieldMeta.addGetForMany(FieldMeta.java:420)
        at io.ebean.enhance.entity.FieldMeta.addGet(FieldMeta.java:347)
        at io.ebean.enhance.entity.FieldMeta.addGetSetMethods(FieldMeta.java:315)
        at io.ebean.enhance.common.ClassMeta.addFieldGetSetMethods(ClassMeta.java:301)
        at io.ebean.enhance.entity.ClassAdapterEntity.visitEnd(ClassAdapterEntity.java:280)
        at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:715)
        at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:394)
        at io.ebean.enhance.Transformer.entityEnhancement(Transformer.java:271)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:227)
        at io.ebean.enhance.Transformer.transform(Transformer.java:182)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:148)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:132)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:66)
        at io.ebean.enhance.maven.AbstractEnhance.executeFor(AbstractEnhance.java:77)
        at io.ebean.enhance.maven.MainEnhanceMojo.execute(MainEnhanceMojo.java:26)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

----

>    @OneToMany(cascade = CascadeType.REMOVE)
>    private LinkedList<CustomPermission> customPermissions;
>
>    @OneToMany(targetEntity = User.class, mappedBy = "id")
>    private ArrayList<User> friends;

We are not allowed to use/define concrete implementation for collections. That is, we are not allowed to use **LinkedList** or **ArrayList** as collection types.  Instead we need to use List (or Set or Map) - so changing LinkedList and ArrayList to java.util.List is what is required here.

That is, change it to:

    @OneToMany(cascade = CascadeType.REMOVE)
    private List<CustomPermission> customPermissions;

    @OneToMany(targetEntity = User.class, mappedBy = "id")
    private List<User> friends;

Q: Why use interface types (java.util.List) and not concrete types (ArrayList) ?
A: Because for these collections the ORM need to be able to implement lazy loading and change tracking (like orphan removal).  So Ebean ORM will provide an implementation of the List interface that does those 2 things - change tracking and lazy loading.

.. but yeah, ideally we detect that somewhere rather than give this unhelpful exception.

**Comment by rbygrave** [comment]
Improve the error to instead be:

```
ebean-enhance> cls: org/example/domain/Hello  msg: Error during transform java.lang.RuntimeException: Unexpected collection type [java.util.LinkedList] for [org/example/domain/Hello.others] expected either java.util.List, java.util.Set or java.util.Map 
java.lang.RuntimeException: Unexpected collection type [java.util.LinkedList] for [org/example/domain/Hello.others] expected either java.util.List, java.util.Set or java.util.Map 
        at io.ebean.enhance.entity.FieldMeta.addGetForMany(FieldMeta.java:412)
        at io.ebean.enhance.entity.FieldMeta.addGet(FieldMeta.java:347)
        at io.ebean.enhance.entity.FieldMeta.addGetSetMethods(FieldMeta.java:315)
        at io.ebean.enhance.common.ClassMeta.addFieldGetSetMethods(ClassMeta.java:301)
        at io.ebean.enhance.entity.ClassAdapterEntity.visitEnd(ClassAdapterEntity.java:280)
        at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:715)
        at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:394)
        at io.ebean.enhance.Transformer.entityEnhancement(Transformer.java:271)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:227)
        at io.ebean.enhance.Transformer.transform(Transformer.java:182)
```
