### ISSUE TITLE
java.lang.NullPointerException 	at io.ebean.enhance.agent.AnnotationInfoVisitor.visitEnd(AnnotationInfoVisitor.java:40) 	at io.ebean.enhance.asm.ClassReader.readAnnotationValues(ClassReader.java:1786)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-agent#41]
```console
java.lang.NullPointerException
	at io.ebean.enhance.agent.AnnotationInfoVisitor.visitEnd(AnnotationInfoVisitor.java:40)
	at io.ebean.enhance.asm.ClassReader.readAnnotationValues(ClassReader.java:1786)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:640)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:506)
	at io.ebean.enhance.agent.ClassMetaReader.readFromResource(ClassMetaReader.java:66)
	at io.ebean.enhance.agent.ClassMetaReader.getWithCache(ClassMetaReader.java:35)
	at io.ebean.enhance.agent.ClassMetaReader.get(ClassMetaReader.java:27)
	at io.ebean.enhance.agent.EnhanceContext.getInterfaceMeta(EnhanceContext.java:147)
	at io.ebean.enhance.agent.ClassAdapterDetectEnhancement.visit(ClassAdapterDetectEnhancement.java:94)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:622)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:506)
	at io.ebean.enhance.agent.Transformer.detect(Transformer.java:259)
	at io.ebean.enhance.agent.Transformer.transform(Transformer.java:118)
	at io.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
	at io.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:64)
```

**Comment by rbygrave** [comment]
Bug in meta data reading of class with @Transactional at class level.
