### ISSUE TITLE
ArrayIndexOutOfBoundsException while calling `enhanceQueryBean`

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/ebean-agent#55]
I often get the following exception (which can be ignored) when calling `Transformer.enhanceQueryBean(ClassLoader loader, TransformRequest request)` method:

```
java.lang.ArrayIndexOutOfBoundsException: 3084
	at io.ebean.enhance.asm.ClassReader.readLabel(ClassReader.java:2251)
	at io.ebean.enhance.asm.ClassReader.readFrameType(ClassReader.java:2231)
	at io.ebean.enhance.asm.ClassReader.readFrame(ClassReader.java:2165)
	at io.ebean.enhance.asm.ClassReader.readCode(ClassReader.java:1356)
	at io.ebean.enhance.asm.ClassReader.readMethod(ClassReader.java:1032)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:708)
	at io.ebean.enhance.asm.ClassReader.accept(ClassReader.java:521)
	at io.ebean.enhance.Transformer.enhanceQueryBean(Transformer.java:253)
	at io.ebean.enhance.Transformer.transform(Transformer.java:134)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.esotericsoftware.reflectasm.AccessClassLoader.defineClass(AccessClassLoader.java:98)
	at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:275)
```

The method the transformer is about to enhance actually has nothing to do with ebean. Question: how can I make ebean transformer to skip those methods?

**Comment by rbygrave** [comment]
I'll close.  Re-open if you can reproduce with 10.3.1
