### ISSUE TITLE
NullPointerException on TxType.SUPPORTS after transactional changes

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-agent#74]
Hi,

After updating to the latest version we get a NullPointerException on @Transactional(type = TxType.SUPPORTS) methods. It looks like the io.ebeaninternal.api.SpiTransactionProxy.isActive() method assumes there always is a transaction, which is not always the case.

I attached a patch with a simple test to demonstrate this (created on commit ea4a3b9), here is the resulting stacktrace:

```
testTransactionalSupports(test.enhancement.SomeTransactionalWithStaticTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.NullPointerException
        at io.ebeaninternal.api.SpiTransactionProxy.isActive(SpiTransactionProxy.java:189)
        at io.ebeaninternal.api.ScopedTransaction.isActive(ScopedTransaction.java:13)
        at io.ebeaninternal.server.transaction.TransactionMap$State.set(TransactionMap.java:73)
        at io.ebeaninternal.server.transaction.DefaultTransactionThreadLocal.set(DefaultTransactionThreadLocal.java:36)
        at io.ebeaninternal.server.transaction.DefaultTransactionScopeManager.set(DefaultTransactionScopeManager.java:52)
        at io.ebeaninternal.api.ScopedTransaction.pop(ScopedTransaction.java:60)
        at io.ebeaninternal.api.ScopedTransaction.complete(ScopedTransaction.java:45)
        at io.ebeaninternal.server.core.DefaultServer.scopedTransactionExit(DefaultServer.java:768)
        at io.ebeaninternal.api.HelpScopeTrans.exit(HelpScopeTrans.java:22)
        at test.model.SomeTransactionalWithStatic.testTransactionalSupports(SomeTransactionalWithStatic.java:29)
        at test.enhancement.SomeTransactionalWithStaticTest.testTransactionalSupports(SomeTransactionalWithStaticTest.java:19)
```

[NPE_SUPPORTS.zip](https://github.com/ebean-orm/ebean-agent/files/1461067/NPE_SUPPORTS.zip)

**Comment by rbygrave** [comment]
Thanks, I have logged this as https://github.com/ebean-orm/ebean/issues/1207

Fixing this issue in Ebean itself (and not the agent).  Closing this agent issue.
