### ISSUE TITLE
Still getting unsupported class file error after upgrading to latest Ebean

### ISSUE THREAD

**Issue by fwgreen** [ebean-orm/ebean-agent#85]
I'm running JDK 11.0.1.  Trying bean enhancement after upgrading to 11.24.1 still results in...
```
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
	at io.ebean.enhance.Transformer.detect(Transformer.java:353)
	at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
	at io.ebean.enhance.Transformer.transform(Transformer.java:153)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
	at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
	at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:125)
	at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:64)
	at io.ebean.enhance.maven.AbstractEnhance.executeFor(AbstractEnhance.java:73)
	at io.ebean.enhance.maven.MainEnhanceMojo.execute(MainEnhanceMojo.java:26)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by rbygrave** [comment]
I did test it against Oracle JDK 11.0.1 and confirmed that it worked for
me.  What hasn't been released yet is a new IntelliJ IDEA enhancer plugin
and a new Gradle plugin (so either of those will still not enhance java 11
bytecode yet).

How are you doing the enhancement?  Maven plugin or tile?  I'll get you to
do is create an example project and share it with me.

Cheers, Rob.

**Comment by rbygrave** [comment]
*> io.ebean.tile:enhancement:5.6 *

Try bumping that to 6.1

**Comment by fwgreen** [comment]
Moving to 6.1 yielded more information:  I was using Eclipse and it seems its default maven repo does not have the current ebean-agent (yet?).  I fired up another Ebean based project in Intellij, which seems to use a different default repo, and it downloaded the current dependencies, and in so doing, updated my local repo and fixed the problem in Eclipse.
```
[ERROR] Failed to execute goal io.ebean:ebean-maven-plugin:11.24.1:enhance (io.ebean.tile:enhancement:6.1::main) on project FlexAbleStaff: Execution io.ebean.tile:enhancement:6.1::main of goal io.ebean:ebean-maven-plugin:11.24.1:enhance failed: Plugin io.ebean:ebean-maven-plugin:11.24.1 or one of its dependencies could not be resolved: Failure to find io.ebean:ebean-agent:jar:11.24.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
Thanks for setting me on the right track!

**Comment by rbygrave** [comment]
Cool.

Note that I have created an empty Java 11 project -
https://github.com/ebean-orm-examples/example-java11
... if someone submitted a PR to create a basic example there that would be
great.

Also happy to take some PR's to update the documentation in -
https://github.com/ebean-orm/website-source


Cheers, Rob.
